### ISSUE TITLE
Goal Page - Edit and Delete Functions

### ISSUE THREAD

**Issue by a4lane** [cse110-sp24-group19/final-project#100]
### Create functions to edit and delete existing goals

**Description**
Functions to be called with event listeners on the pen and trash can icons

### Sub-tasks

- [x] Edit Function
- [x] Delete Function

### Estimated Effort
Medium

### Priority
High

### Assignees

@Charlitoes 

### Labels
Sprint 2, High Priority

**Comment by Charlitoes** [comment]
just need someone to review the pr then we can close this issue
