### ISSUE TITLE
Create functional links for the (?) button on the main page

### ISSUE THREAD

**Issue by rianaali** [cse110-sp24-group19/final-project#117]
### Task Description

**Description:**

On the main page, add links to the main categories description list so when the user hovers over the question mark button and the list, they can click on each category to access the respective page.

**Related User Story:**

### Sub-tasks

- [ ] 
- [ ] 
- [ ] 

### Estimated Effort

Medium

### Priority

Medium

**Comment by milgor931** [comment]
Fixed this by getting rid of the question mark and updating the images to be more explicit in what they do.
