### ISSUE TITLE
Fix the Goal-Settings page left offset on a mobile view

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#157]
### Task Description

**Description:**

### Sub-tasks

- [ ] Update CSS styling

### Estimated Effort
Super low ~ 15 min

### Priority
Medium

### Additional Information
![image](https://github.com/cse110-sp24-group19/final-project/assets/40010548/2308e3c9-1a11-4c15-83ed-fbc6ede2c0e9)

### Assignees
@milgor931

**Comment by a4lane** [comment]
just opened this on my phone and it looks good to me

**Comment by Charlitoes** [comment]
![image](https://github.com/cse110-sp24-group19/final-project/assets/144288475/f7de6462-75d3-46d2-a5c2-a3663308289a)

Looks fine when i used the iphone 14 pro max dimensions

**Comment by Charlitoes** [comment]
It actually looks fine with the majority of mobile phones so Ill close this issue, Ill make another issue if this problem arises
