### ISSUE TITLE
Make the Rewards Page more Responsive

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#158]
### Task Description

**Description:**
Make the rewards page more responsive on a mobile view

**Related User Story:**
Accessible and Intuitive Navigation
User Story: As a young adult, I want to navigate the interface intuitively to maximize my productivity.

### Sub-tasks

- [ ] Use CSS flexbox and other styling tools to make this page more responsive

### Estimated Effort
Medium depending on how good you are with CSS flexbox

### Priority
High

### Additional Information
![image](https://github.com/cse110-sp24-group19/final-project/assets/40010548/7a726f8b-f79e-4b96-8849-d08cbef74ebe)

**Comment by Charlitoes** [comment]
PR #201
