### ISSUE TITLE
ESC in Calendar View

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#172]
### Task Description

**Description:**
In the calendar view and goal-setting views, if you press "esc", then you should be able to exit out of the edit entry/edit task mode

**Related User Story:**
Accessible and Intuitive Navigation
User Story: As a young adult, I want to navigate the interface intuitively in order to maximize my productivity.

### Sub-tasks

- [x] ESC for calendar view
- [ ] ESC for goal-settings view

### Estimated Effort
Medium

### Priority
Low

**Comment by bpanuco11** [comment]
I will take care of the Esc functionality on the Calendar view once the search implementation is done.
