### ISSUE TITLE
Update README.md with user manual

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#238]
Update the README.md to discuss the different pages, special abilities, how to use the webapp, etc.

**Comment by gingersmith4** [comment]
<img width="462" alt="Screenshot 2024-06-09 at 4 59 19 PM" src="https://github.com/cse110-sp24-group19/final-project/assets/88351672/ad168318-1f7c-4922-8518-f22f947b82dd">
Here's a general diagram I made on the Miro, do y'all want to add it to the repo or should I? https://miro.com/app/board/uXjVKMn1_cg=/?moveToWidget=3458764587663270928&cot=14
