### ISSUE TITLE
Code quality via human review (ex. Pull Requests)

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#3]

**Comment by nikothomas** [comment]
Added branch protection rules, see announcement #9. Will see what Charlie thinks before closing this issue.

**Comment by Charlitoes** [comment]
I think the branch rules for the main branch are adequate enough to protect it from being accidentally overwritten and having at least one person reviewing the code, be it me or another person to make sure it won't break anything in main is a nice addition for the rules. Thank you Nik!

**Comment by nikothomas** [comment]
Lock Branch: 'main' is read-only. Users cannot push to 'main'
also prevented PR's so it's been removed, the branch protection should be stable now.
