### ISSUE TITLE
Notification system as reminders

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#30]
### Task Description

**Description:**
Frequency based on category (daily, weekly, long-term). Shows up when you first access the webapp.

**Related User Story:**
Goal-Setting
User Story: As a young adult, I want to set goals in order to achieve my biggest dreams in life. 

### Sub-tasks

- [ ] User gets alert notifications regarding which daily tasks they need to complete when they open the application 
- [ ] User gets alert notifications regarding which weekly tasks they need to complete when they open the application 

### Estimated Effort
Medium

### Priority
Low

### Assignees
@Charlitoes

**Comment by Charlitoes** [comment]
I will work on this once the goals page is finished

**Comment by milgor931** [comment]
I don't think this is necessary anymore. It is more important to prioritize the search/filtration system and debug the webapp before adding on new features like this one.
