### ISSUE TITLE
phase1.png - a diagram of your phase 1 build pipeline (can be phase1.drawio.png if using draw.io)

### ISSUE THREAD

**Issue by milgor931** [cse110-sp24-group19/final-project#6]

**Comment by gingersmith4** [comment]
Created pull request with upload, the diagram is on our [Miro board](https://miro.com/app/board/uXjVKMn1_cg=/?share_link_id=750061756326).

**Comment by gingersmith4** [comment]
Based on the branch protection rules: https://github.com/cse110-sp24-group19/final-project/discussions/9

**Comment by nikothomas** [comment]
Forgot to wait for the status check/approval order to be flipped before accepting the PR
